#!/usr/bin/with-contenv bash
# shellcheck shell=bash


# Bump php upload max filesize and post max size to 100MB by default
if ! grep -qx '^upload_max_filesize.*$' /config/php/php-local.ini; then
    echo 'upload_max_filesize = 100M' >>/config/php/php-local.ini
fi
if ! grep -qx '^post_max_size.*$' /config/php/php-local.ini; then
    echo 'post_max_size = 100M' >>/config/php/php-local.ini
fi

ENV_FILE="/app/www/.env"
if [ ! -f "$ENV_FILE" ]; then
    echo "The configuration file is missing (.env)."
    exit 1
else
    source "$ENV_FILE"
fi

echo "Waiting for database connection..."
DB_HOST="${DB_HOST:-mysql}"
DB_PORT="${DB_PORT:-3306}"
DB_USERNAME="${DB_USERNAME:-kanka}"
DB_PASSWORD="${DB_PASSWORD:-}"
DB_DATABASE="${DB_DATABASE:-kanka}"

while ! mariadb -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USERNAME" -p"$DB_PASSWORD" "$DB_DATABASE" \
        -e "SELECT 1" >/dev/null 2>&1
do
    sleep 5
done

# One time setup
FLAG_FILE="/app/www/storage/installed.flag"
if [ ! -f "$FLAG_FILE" ]; then
    mkdir -p /app/www/storage/{app,fonts,framework,logs,purify}
    mkdir -p /app/www/storage/framework/{cache/data,sessions,testing,views}
    echo "Running initial Kanka CE installation"
    php /app/www/artisan kanka:install
    touch "$FLAG_FILE"
    echo "Installation complete"
fi

# update database - will set up database if fresh, or, migrate existing
php /app/www/artisan migrate --force

# permissions
# TODO use /config here
lsiown -R abc:abc \
    /app/www/storage
