#!/usr/bin/with-contenv bash
# shellcheck shell=bash


# Bump php upload max filesize and post max size to 100MB by default
if ! grep -qx '^upload_max_filesize.*$' /config/php/php-local.ini; then
    echo 'upload_max_filesize = 100M' >>/config/php/php-local.ini
fi
if ! grep -qx '^post_max_size.*$' /config/php/php-local.ini; then
    echo 'post_max_size = 100M' >>/config/php/php-local.ini
fi

# if DB_PORT is not set
if [[ -z "${DB_PORT}" ]]; then
    DB_PORT="3306"
fi

# check for the mysql endpoint
echo "Waiting for DB to be available"
END=$((SECONDS + 30))
while [[ ${SECONDS} -lt ${END} ]] && [[ -n "${DB_HOST+x}" ]]; do
    if [[ $(/usr/bin/nc -w1 "${DB_HOST}" "${DB_PORT}" | tr -d '\0') ]]; then
        if [[ ! -f /tmp/dbwait.lock ]]; then
            sleep 5
        fi
        touch /tmp/dbwait.lock
        break
    else
        sleep 1
    fi
done

# One time setup
FLAG_FILE="/app/www/storage/installed.flag"
if [ ! -f "$FLAG_FILE" ]; then
    mkdir -p /app/www/storage/{app,fonts,framework,logs,purify}
    mkdir -p /app/www/storage/framework/{cache/data,sessions,testing,views}
    echo "Running initial Kanka CE installation"
    php /app/www/artisan kanka:install
    touch "$FLAG_FILE"
    echo "Installation complete"
fi

# update database - will set up database if fresh, or, migrate existing
php /app/www/artisan migrate --force

# permissions
# TODO use /config here
lsiown -R abc:abc \
    /app/www/storage
